alter table public.posts
  add column if not exists preview_url text,
  add column if not exists storage_path text,
  add column if not exists file_name text,
  add column if not exists file_type text;

create table if not exists public.albums (
  id bigint generated by default as identity primary key,
  user_id text not null,
  title text not null,
  description text default '',
  is_public boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.album_photos (
  id bigint generated by default as identity primary key,
  album_id bigint not null references public.albums(id) on delete cascade,
  post_id bigint not null references public.posts(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (album_id, post_id)
);

create unique index if not exists likes_post_user_unique
  on public.likes (post_id, user_id);
