import {auth,rtdb,ref,set,update,remove,get,onValue,onDisconnect,rtdbTimestamp,push,runRTDBTransaction,profileFor,onAuthStateChanged} from './firebase.js';
const $=s=>document.querySelector(s),msg=t=>{$('#multiMessage').textContent=t};let user,profile,roomId,roomOff;
function code(){return Math.random().toString(36).slice(2,8).toUpperCase()}
async function requirePlayer(){user=auth.currentUser||await new Promise(resolve=>{const off=onAuthStateChanged(auth,u=>{off();resolve(u)})});if(!user){location.href='login.html?next=multiplayer.html';return false}profile=await profileFor(user.uid);if(!profile){location.href='setup-profile.html';return false}return true}
async function createRoom(type='reaction',isPublic=false){if(!await requirePlayer())return;roomId=code();await set(ref(rtdb,`rooms/${roomId}`),{id:roomId,type,public:isPublic,status:'waiting',host:user.uid,createdAt:rtdbTimestamp,players:{[user.uid]:{name:profile.displayName,ready:false,score:null}}});await set(ref(rtdb,`openRooms/${roomId}`),isPublic?{type,createdAt:rtdbTimestamp}:null);watch(roomId)}
async function joinRoom(id){if(!await requirePlayer())return;id=id.trim().toUpperCase();const snap=await get(ref(rtdb,`rooms/${id}`));if(!snap.exists())throw new Error('Room not found.');const room=snap.val();if(room.status!=='waiting')throw new Error('That match already started.');if(Object.keys(room.players||{}).length>=2&&!room.players[user.uid])throw new Error('Room is full.');roomId=id;await update(ref(rtdb,`rooms/${id}/players/${user.uid}`),{name:profile.displayName,ready:false,score:null});await remove(ref(rtdb,`openRooms/${id}`));watch(id)}
function watch(id){history.replaceState(null,'',`?room=${id}`);$('#lobby').hidden=true;$('#room').hidden=false;$('#roomCode').textContent=id;const rr=ref(rtdb,`rooms/${id}`);onDisconnect(ref(rtdb,`rooms/${id}/players/${user.uid}`)).remove();onValue(rr,s=>{if(!s.exists()){msg('Room closed.');return}render(s.val())});}
function render(room){const players=Object.entries(room.players||{});$('#players').innerHTML=players.map(([uid,p])=>`<div class="player-row"><span>${p.name}${uid===user.uid?' (you)':''}</span><strong>${p.ready?'Ready':'Waiting'}</strong></div>`).join('');$('#ready').disabled=players.length<2;if(room.status==='playing')location.href=`battle.html?room=${room.id}`;}
$('#createPrivate').onclick=()=>createRoom($('#gameType').value,false).catch(e=>msg(e.message));$('#createPublic').onclick=()=>createRoom($('#gameType').value,true).catch(e=>msg(e.message));$('#joinForm').onsubmit=e=>{e.preventDefault();joinRoom($('#joinCode').value).catch(err=>msg(err.message))};$('#ready').onclick=async()=>{await set(ref(rtdb,`rooms/${roomId}/players/${user.uid}/ready`),true);const s=await get(ref(rtdb,`rooms/${roomId}`)),r=s.val(),ps=Object.values(r.players||{});if(ps.length===2&&ps.every(p=>p.ready)){await update(ref(rtdb,`rooms/${roomId}`),{status:'playing',seed:Math.floor(Math.random()*1e9),startedAt:rtdbTimestamp});}};$('#leave').onclick=async()=>{await remove(ref(rtdb,`rooms/${roomId}/players/${user.uid}`));location.href='multiplayer.html'};
$('#matchmake').onclick=async()=>{if(!await requirePlayer())return;msg('Looking for a public match…');const open=await get(ref(rtdb,'openRooms'));const list=open.val()||{};const wanted=$('#gameType').value,found=Object.keys(list).find(k=>list[k].type===wanted);if(found)return joinRoom(found).catch(async()=>createRoom(wanted,true));createRoom(wanted,true)};
(async()=>{if(!await requirePlayer())return;const id=new URLSearchParams(location.search).get('room');if(id)joinRoom(id).catch(e=>msg(e.message))})();
