import {auth,db,rtdb,onAuthStateChanged,doc,getDoc,setDoc,updateDoc,deleteDoc,serverTimestamp,collection,query,where,getDocs,ref,get,onValue} from './firebase.js';
const $=s=>document.querySelector(s),esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));let user=null,profile=null,relationships=[],presenceStop=null;
const pair=(a,b)=>[a,b].sort().join('_');function notice(text,bad=false){const el=$('#socialMessage');el.textContent=text;el.className=`message ${bad?'error':'success'}`}
async function boot(){user=await new Promise(resolve=>{const stop=onAuthStateChanged(auth,u=>{stop();resolve(u)})});if(!user||user.isAnonymous)return location.replace('login.html?next=friends.html');const own=await getDoc(doc(db,'users',user.uid));if(!own.exists()||!own.data().displayName)throw new Error('Finish your profile before using Friends.');profile=own.data();await setDoc(doc(db,'publicProfiles',user.uid),publicData(user.uid,profile),{merge:true});$('#searchForm').onsubmit=search;await refresh();presenceStop=onValue(ref(rtdb,'socialPresence'),snap=>renderFriends(relationships.filter(x=>x.status==='accepted'),snap.val()||{}),e=>notice(`Friend presence unavailable: ${e.message}`,true))}
function publicData(uid,data){return {uid,displayName:data.displayName,photoURL:data.photoURL||'',usernameKey:data.usernameKey||data.displayName.toLowerCase(),statsVisible:data.statsVisible!==false,activityVisible:data.activityVisible!==false,joinPolicy:data.joinPolicy||'friends',updatedAt:serverTimestamp()}}
async function refresh(){try{const snap=await getDocs(query(collection(db,'friendships'),where('members','array-contains',user.uid)));relationships=snap.docs.map(d=>({id:d.id,...d.data()}));const incoming=relationships.filter(x=>x.status==='pending'&&x.requestedBy!==user.uid),sent=relationships.filter(x=>x.status==='pending'&&x.requestedBy===user.uid),friends=relationships.filter(x=>x.status==='accepted'),blocked=relationships.filter(x=>x.status==='blocked'&&x.blockedBy===user.uid);$('#requestCount').textContent=incoming.length;renderRequests(incoming,sent);renderBlocked(blocked);const p=(await get(ref(rtdb,'socialPresence'))).val()||{};renderFriends(friends,p)}catch(e){throw new Error(`Could not load friends: ${friendly(e)}`)}}
async function search(event){event.preventDefault();notice('');const key=$('#friendSearch').value.trim().toLowerCase();$('#searchResult').innerHTML='<div class="social-loading">Searching…</div>';try{if(!key)throw new Error('Enter an exact display name.');const name=await getDoc(doc(db,'usernames',key));if(!name.exists())throw new Error('No player found with that exact display name.');const uid=name.data().uid;if(uid===user.uid)throw new Error('That is your own account.');let pub=await getDoc(doc(db,'publicProfiles',uid));const data=pub.exists()?pub.data():{uid,displayName:name.data().displayName||$('#friendSearch').value.trim(),statsVisible:true};const existing=relationships.find(x=>x.members?.includes(uid));$('#searchResult').innerHTML=profileCard(data,existing)}catch(e){$('#searchResult').innerHTML=`<div class="empty-state compact">${esc(e.message)}</div>`}}
function profileCard(p,rel){let action=`<button class="button" data-add="${p.uid}" data-name="${esc(p.displayName)}">Add friend</button>`;if(rel?.status==='accepted')action='<span class="social-tag success">Friends</span>';if(rel?.status==='pending')action='<span class="social-tag">Request pending</span>';if(rel?.status==='blocked')action='<span class="social-tag danger">Blocked</span>';return `<article class="friend-card"><div class="friend-avatar">${esc(p.displayName?.[0]||'?')}</div><div><h3>${esc(p.displayName||'Player')}</h3><p>Human Skills Tester player</p></div><div class="friend-actions"><a class="button secondary" href="player.html?uid=${encodeURIComponent(p.uid)}">View stats</a>${action}</div></article>`}
document.addEventListener('click',event=>{const button=event.target.closest('[data-add]');if(button)sendRequest(button.dataset.add,button.dataset.name).catch(e=>notice(friendly(e),true))});
async function sendRequest(uid,name){if(!uid||uid===user.uid)throw new Error('Invalid friend request.');const id=pair(user.uid,uid),existing=await getDoc(doc(db,'friendships',id));if(existing.exists())throw new Error('A friend request or friendship already exists.');await setDoc(doc(db,'friendships',id),{members:[user.uid,uid].sort(),names:{[user.uid]:profile.displayName,[uid]:name},requestedBy:user.uid,status:'pending',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});notice(`Friend request sent to ${name}.`);await refresh()}
function other(rel){return rel.members.find(id=>id!==user.uid)}function requestRow(rel,incoming){const uid=other(rel),name=rel.names?.[uid]||'Player';return `<div class="request-row"><span>${esc(name)}</span><div>${incoming?`<button class="button" data-accept="${rel.id}">Accept</button>`:''}<button class="button secondary" data-decline="${rel.id}">${incoming?'Decline':'Cancel'}</button></div></div>`}
function renderRequests(incoming,sent){$('#incoming').innerHTML=incoming.length?incoming.map(x=>requestRow(x,true)).join(''):'<div class="empty-state compact">No incoming requests.</div>';$('#sent').innerHTML=sent.length?sent.map(x=>requestRow(x,false)).join(''):'<div class="empty-state compact">No sent requests.</div>'}
document.addEventListener('click',event=>{const accept=event.target.closest('[data-accept]'),decline=event.target.closest('[data-decline]'),remove=event.target.closest('[data-remove]'),blockButton=event.target.closest('[data-block]'),unblock=event.target.closest('[data-unblock]');if(accept)acceptRequest(accept.dataset.accept).catch(e=>notice(friendly(e),true));if(decline)deleteRelationship(decline.dataset.decline).catch(e=>notice(friendly(e),true));if(remove)deleteRelationship(remove.dataset.remove).catch(e=>notice(friendly(e),true));if(blockButton)block(blockButton.dataset.block).catch(e=>notice(friendly(e),true));if(unblock)deleteRelationship(unblock.dataset.unblock).catch(e=>notice(friendly(e),true))});
async function acceptRequest(id){const snap=await getDoc(doc(db,'friendships',id));if(!snap.exists()||snap.data().requestedBy===user.uid)throw new Error('Only the recipient can accept this request.');await updateDoc(doc(db,'friendships',id),{status:'accepted',acceptedAt:serverTimestamp(),updatedAt:serverTimestamp()});notice('Friend request accepted.');await refresh()}async function deleteRelationship(id){await deleteDoc(doc(db,'friendships',id));notice('Relationship removed.');await refresh()}async function block(id){await updateDoc(doc(db,'friendships',id),{status:'blocked',blockedBy:user.uid,updatedAt:serverTimestamp()});notice('Player blocked.');await refresh()}
function renderFriends(list,presence={}){if(!list.length){$('#friendsList').innerHTML='<div class="empty-state">No friends yet. Search for an exact display name to get started.</div>';return}$('#friendsList').innerHTML=list.map(rel=>{const uid=other(rel),name=rel.names?.[uid]||'Player',live=presence[uid]||{},online=live.state==='online',join=online&&live.joinable&&live.roomId?`<a class="button" href="multiplayer.html?room=${encodeURIComponent(live.roomId)}">Join game</a>`:'';return `<article class="friend-card"><div class="friend-avatar ${online?'online':''}">${esc(name[0])}</div><div><h3>${esc(name)}</h3><p>${online?activity(live):'Offline'}</p></div><div class="friend-actions">${join}<a class="button secondary" href="player.html?uid=${encodeURIComponent(uid)}">View stats</a><button class="text-button danger-text" data-remove="${rel.id}">Remove</button><button class="text-button" data-block="${rel.id}">Block</button></div></article>`}).join('')}
function activity(p){return p.activity==='multiplayer'?`${p.joinable?'Joinable':'Playing'} · ${p.gameType||'game'} · ${p.rounds||1} rounds`:'Online'}function renderBlocked(list){$('#blocked').innerHTML=list.length?list.map(x=>`<div class="request-row"><span>${esc(x.names?.[other(x)]||'Player')}</span><button class="button secondary" data-unblock="${x.id}">Unblock</button></div>`).join(''):'<div class="empty-state compact">No blocked players.</div>'}function friendly(e){if(e?.code==='permission-denied')return 'Firebase rules denied this action. Publish the included Firestore rules.';return e?.message||'Something went wrong.'}boot().catch(e=>notice(friendly(e),true));
