import {auth,db,onAuthStateChanged,doc,setDoc,deleteDoc,serverTimestamp,collection,getDocs} from './firebase.js';
let currentUser=null,currentProfile=null,syncing=false;
const scoreDoc=(uid,key)=>doc(db,'users',uid,'scores',key),boardDoc=(key,uid)=>doc(db,'leaderboards',key,'entries',uid);
function better(key,a,b){if(a==null)return b;if(b==null)return a;return HST.lowerIsBetter.has(key)?Math.min(a,b):Math.max(a,b)}
async function publish(key,value){if(!currentUser||currentUser.isAnonymous)return;await setDoc(boardDoc(key,currentUser.uid),{uid:currentUser.uid,displayName:currentProfile?.displayName||currentUser.displayName||'Player',value:Number(value),updatedAt:serverTimestamp()},{merge:true})}
async function syncScores(user){if(syncing||user.isAnonymous)return;syncing=true;document.documentElement.dataset.scoreSync='loading';try{const userSnap=await getDocs(collection(db,'users',user.uid,'scores')),profileSnap=await import('./firebase.js').then(m=>m.getDoc(m.doc(db,'users',user.uid)));currentProfile=profileSnap.exists()?profileSnap.data():null;const cloud={};userSnap.forEach(d=>{const v=Number(d.data().value);if(Number.isFinite(v))cloud[d.id]=v});for(const key of Object.keys(HST.keys)){const local=HST.get(key),merged=better(key,local,cloud[key]);if(merged!=null){localStorage.setItem(HST.keys[key],String(merged));if(cloud[key]!==merged)await setDoc(scoreDoc(user.uid,key),{value:merged,updatedAt:serverTimestamp()},{merge:true});await publish(key,merged)}}document.documentElement.dataset.scoreSync='ready';window.dispatchEvent(new Event('hst:scores-changed'))}catch(e){console.error('Score sync failed',e);document.documentElement.dataset.scoreSync='error';window.dispatchEvent(new CustomEvent('hst:sync-error',{detail:e}))}finally{syncing=false}}
onAuthStateChanged(auth,user=>{currentUser=user&&!user.isAnonymous?user:null;if(currentUser)syncScores(currentUser);else window.dispatchEvent(new Event('hst:scores-changed'))});
const original=HST.setBest.bind(HST);HST.setBest=(key,value,lower=HST.lowerIsBetter.has(key))=>{const won=original(key,value,lower);if(won&&currentUser){setDoc(scoreDoc(currentUser.uid,key),{value:Number(value),updatedAt:serverTimestamp()},{merge:true}).then(()=>publish(key,value)).catch(console.error)}return won};
window.addEventListener('hst:reset-requested',async()=>{Object.values(HST.keys).forEach(k=>localStorage.removeItem(k));if(currentUser){const snap=await getDocs(collection(db,'users',currentUser.uid,'scores'));await Promise.all([...snap.docs.map(d=>deleteDoc(d.ref)),...Object.keys(HST.keys).map(key=>deleteDoc(boardDoc(key,currentUser.uid)))])}location.reload()});
