import {auth,db,onAuthStateChanged,GoogleAuthProvider,signInWithPopup,signInWithRedirect,getRedirectResult,createUserWithEmailAndPassword,signInWithEmailAndPassword,sendPasswordResetEmail,sendEmailVerification,signInWithCredential,doc,getDoc,friendlyError,GOOGLE_CLIENT_ID} from './firebase.js';
const $=s=>document.querySelector(s), message=(text,bad=false)=>{const e=$('#authMessage');if(e){e.textContent=text;e.className='auth-message '+(bad?'bad':'good')}};
async function destination(user){const p=await getDoc(doc(db,'users',user.uid));location.href=p.exists()?'index.html':'setup-profile.html'}
async function google(){const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});try{const result=matchMedia('(max-width: 650px)').matches?await (signInWithRedirect(auth,provider),null):await signInWithPopup(auth,provider);if(result)await destination(result.user)}catch(e){if(e.code==='auth/popup-blocked')return signInWithRedirect(auth,provider);message(friendlyError(e),true)}}
document.querySelectorAll('[data-google]').forEach(b=>b.onclick=google);
getRedirectResult(auth).then(r=>r&&destination(r.user)).catch(e=>message(friendlyError(e),true));
const login=$('#loginForm');if(login)login.onsubmit=async e=>{e.preventDefault();try{const r=await signInWithEmailAndPassword(auth,$('#email').value,$('#password').value);await destination(r.user)}catch(err){message(friendlyError(err),true)}};
const signup=$('#signupForm');if(signup)signup.onsubmit=async e=>{e.preventDefault();if($('#password').value!==$('#confirm').value)return message('Passwords do not match.',true);try{const r=await createUserWithEmailAndPassword(auth,$('#email').value,$('#password').value);await sendEmailVerification(r.user);location.href='setup-profile.html'}catch(err){message(friendlyError(err),true)}};
const forgot=$('#forgot');if(forgot)forgot.onclick=async()=>{const email=$('#email').value.trim();if(!email)return message('Enter your email first.',true);try{await sendPasswordResetEmail(auth,email);message('Password reset email sent.')}catch(e){message(friendlyError(e),true)}};
window.handleGoogleCredential=async response=>{try{const credential=GoogleAuthProvider.credential(response.credential);const r=await signInWithCredential(auth,credential);await destination(r.user)}catch(e){message(friendlyError(e),true)}};
function initOneTap(){if(!$('#oneTap')||!window.google)return false;google.accounts.id.initialize({client_id:GOOGLE_CLIENT_ID,callback:window.handleGoogleCredential,auto_select:false,cancel_on_tap_outside:true});google.accounts.id.renderButton($('#oneTap'),{theme:'outline',size:'large',width:320});google.accounts.id.prompt();return true}if(!initOneTap()){let tries=0;const wait=setInterval(()=>{if(initOneTap()||++tries>30)clearInterval(wait)},100)}
