import {auth,rtdb,ref,get,onValue,update,set,rtdbTimestamp,profileFor,onAuthStateChanged} from './firebase.js';
const $=s=>document.querySelector(s),params=new URLSearchParams(location.search),roomId=params.get('room');let user,room,started=0,timer,question=0,score=0,solution=0,finished=false;
function seeded(seed){let x=seed%2147483647;return()=>((x=x*16807%2147483647)-1)/2147483646}
async function boot(){user=auth.currentUser||await new Promise(resolve=>{const off=onAuthStateChanged(auth,u=>{off();resolve(u)})});if(!user)return location.replace('login.html');const p=await profileFor(user.uid);const snap=await get(ref(rtdb,`rooms/${roomId}`));if(!snap.exists())return fail('Room no longer exists.');room=snap.val();if(!room.players?.[user.uid])return fail('You are not a player in this room.');$('#battleTitle').textContent=({reaction:'Reaction Duel',math:'Math Race',typing:'Typing Race'})[room.type];onValue(ref(rtdb,`rooms/${roomId}`),s=>s.exists()&&renderStatus(s.val()));startGame();}
function fail(t){$('#arena').innerHTML=`<h2>${t}</h2><a class="button" href="multiplayer.html">Back to multiplayer</a>`}
function renderStatus(r){room=r;$('#battlePlayers').innerHTML=Object.values(r.players||{}).map(p=>`<span class="result-chip">${p.name}: ${!p.finished?'playing':p.score}</span>`).join('');const vals=Object.values(r.players||{});if(vals.length===2&&vals.every(p=>p.finished===true)){const best=r.type==='reaction'?Math.min(...vals.map(p=>p.score)):Math.max(...vals.map(p=>p.score));const mine=r.players[user.uid].score;$('#outcome').textContent=mine===best&&(vals.filter(p=>p.score===best).length===1)?'You win!':mine===best?'Tie game':'Opponent wins';$('#rematch').hidden=false;}}
function startGame(){if(room.type==='reaction')reaction();if(room.type==='math')math();if(room.type==='typing')typing()}
function reaction(){const delay=1800+(room.seed%2500);$('#game').innerHTML='<button id="reaction" class="reaction-zone waiting"><span class="readout">Wait</span></button>';const z=$('#reaction');let ready=false;timer=setTimeout(()=>{ready=true;started=performance.now();z.className='reaction-zone ready';z.innerHTML='<span class="readout">Click!</span>'},delay);z.onclick=()=>{if(finished)return;if(!ready){clearTimeout(timer);finish(9999,'False start')}else finish(Math.round(performance.now()-started),'Finished')}}
function math(){const rand=seeded(room.seed),end=Date.now()+30000;$('#game').innerHTML='<div class="result-row"><span class="result-chip">30 seconds</span><span id="myScore" class="result-chip">0 correct</span></div><div id="problem" class="math-problem"></div><form id="answerForm" class="controls"><input id="answer" class="input" type="number" inputmode="numeric"><button class="button">Answer</button></form>';function next(){let a=2+Math.floor(rand()*18),b=2+Math.floor(rand()*12);solution=a+b;$('#problem').textContent=`${a} + ${b}`;$('#answer').value='';$('#answer').focus()}$('#answerForm').onsubmit=e=>{e.preventDefault();if(Number($('#answer').value)===solution){score++;$('#myScore').textContent=`${score} correct`;next()}else $('#answer').select()};next();timer=setInterval(()=>{if(Date.now()>=end){clearInterval(timer);finish(score,'Time')}},100)}
function typing(){const texts=['Practice makes progress when every player stays focused and calm.','Fast fingers help, but careful accuracy wins the final typing race.'],text=texts[room.seed%texts.length];$('#game').innerHTML=`<div class="typing-text">${text}</div><textarea id="typeInput" class="typing-input" placeholder="Type here"></textarea><p id="typingStat" class="message">Start typing</p>`;const inp=$('#typeInput');inp.oninput=()=>{if(!started)started=performance.now();let correct=0;for(let i=0;i<inp.value.length;i++)if(inp.value[i]===text[i])correct++;const pct=Math.round(correct/text.length*100);$('#typingStat').textContent=`${pct}% complete`;if(inp.value===text){const sec=(performance.now()-started)/1000,wpm=Math.round((text.length/5)/(sec/60));finish(wpm,`${wpm} WPM`)}};inp.focus()}
async function finish(value,label){if(finished)return;finished=true;$('#outcome').textContent=label;await update(ref(rtdb,`rooms/${roomId}/players/${user.uid}`),{score:value,finished:true,finishedAt:rtdbTimestamp()});}
$('#rematch').onclick=async()=>{const updates={status:'waiting',seed:null,startedAt:null};for(const uid of Object.keys(room.players))updates[`players/${uid}/ready`]=false,updates[`players/${uid}/score`]=0,updates[`players/${uid}/finished`]=false;await update(ref(rtdb,`rooms/${roomId}`),updates);location.href=`multiplayer.html?room=${roomId}`};boot();
