import {auth,db,GoogleAuthProvider,signInWithPopup,signInWithRedirect,getRedirectResult,createUserWithEmailAndPassword,signInWithEmailAndPassword,sendPasswordResetEmail,sendEmailVerification,signInWithCredential,doc,getDoc,friendlyError,GOOGLE_CLIENT_ID} from './firebase.js';
const $=s=>document.querySelector(s);const message=(text,bad=false)=>{const e=$('#authMessage');if(e){e.textContent=text;e.className='auth-message '+(bad?'bad':'good')}};
async function destination(user){const next=new URLSearchParams(location.search).get('next');const p=await getDoc(doc(db,'users',user.uid));location.href=p.exists()?(next||'index.html'):'setup-profile.html'}
async function googleFirebase(){const provider=new GoogleAuthProvider();provider.setCustomParameters({prompt:'select_account'});try{if(matchMedia('(max-width:650px)').matches){sessionStorage.setItem('hst_auth_redirect','1');await signInWithRedirect(auth,provider);return}await destination((await signInWithPopup(auth,provider)).user)}catch(e){if(e.code==='auth/popup-blocked'){await signInWithRedirect(auth,provider);return}message(friendlyError(e),true)}}
document.querySelectorAll('[data-google]').forEach(b=>b.addEventListener('click',googleFirebase));
getRedirectResult(auth).then(r=>{if(r)destination(r.user);else if(sessionStorage.getItem('hst_auth_redirect'))sessionStorage.removeItem('hst_auth_redirect')}).catch(e=>message(friendlyError(e),true));
const login=$('#loginForm');if(login)login.addEventListener('submit',async e=>{e.preventDefault();try{await destination((await signInWithEmailAndPassword(auth,$('#email').value.trim(),$('#password').value)).user)}catch(err){message(friendlyError(err),true)}});
const signup=$('#signupForm');if(signup)signup.addEventListener('submit',async e=>{e.preventDefault();if($('#password').value!==$('#confirm').value)return message('Passwords do not match.',true);try{const r=await createUserWithEmailAndPassword(auth,$('#email').value.trim(),$('#password').value);await sendEmailVerification(r.user);location.href='setup-profile.html'}catch(err){message(friendlyError(err),true)}});
const forgot=$('#forgot');if(forgot)forgot.addEventListener('click',async()=>{const email=$('#email').value.trim();if(!email)return message('Enter your email first.',true);try{await sendPasswordResetEmail(auth,email);message('Password reset email sent.')}catch(e){message(friendlyError(e),true)}});
async function handleCredential(response){try{const credential=GoogleAuthProvider.credential(response.credential);await destination((await signInWithCredential(auth,credential)).user)}catch(e){message(friendlyError(e),true)}}
function initGIS(){if(!window.google?.accounts?.id)return false;try{google.accounts.id.initialize({client_id:GOOGLE_CLIENT_ID,callback:handleCredential,auto_select:false,cancel_on_tap_outside:false,use_fedcm_for_prompt:true});const target=$('#oneTap');if(target){target.innerHTML='';google.accounts.id.renderButton(target,{theme:'outline',size:'large',shape:'rectangular',text:'continue_with',width:Math.min(360,target.clientWidth||360)});google.accounts.id.prompt(n=>{if(n.isNotDisplayed?.())message('One Tap is unavailable in this browser. Use the Google button below.',false)})}return true}catch(e){console.warn('Google Identity initialization failed',e);return false}}
window.addEventListener('load',()=>{if(initGIS())return;let tries=0;const id=setInterval(()=>{if(initGIS()||++tries>=50)clearInterval(id)},100)});
