import {auth,db,rtdb,onAuthStateChanged,doc,getDoc,setDoc,updateDoc,deleteDoc,serverTimestamp,collection,query,where,getDocs,ref,get,onValue} from './firebase.js';
const $=s=>document.querySelector(s),esc=v=>String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));let user,profile,relationships=[];
const pair=(a,b)=>[a,b].sort().join('_');
function notice(t,bad=false){$('#socialMessage').textContent=t;$('#socialMessage').className=`message ${bad?'error':''}`}
async function boot(){user=await new Promise(r=>{const off=onAuthStateChanged(auth,u=>{off();r(u)})});if(!user||user.isAnonymous)return location.replace('login.html?next=friends.html');profile=(await getDoc(doc(db,'users',user.uid))).data();$('#searchForm').onsubmit=search;await refresh()}
async function refresh(){const snap=await getDocs(query(collection(db,'friendships'),where('members','array-contains',user.uid)));relationships=snap.docs.map(d=>({id:d.id,...d.data()}));const incoming=relationships.filter(x=>x.status==='pending'&&x.requestedBy!==user.uid),sent=relationships.filter(x=>x.status==='pending'&&x.requestedBy===user.uid),friends=relationships.filter(x=>x.status==='accepted'),blocked=relationships.filter(x=>x.status==='blocked'&&x.blockedBy===user.uid);$('#requestCount').textContent=incoming.length;renderRequests(incoming,sent);await renderFriends(friends);renderBlocked(blocked)}
async function search(e){e.preventDefault();const raw=$('#friendSearch').value.trim(),key=raw.toLowerCase();$('#searchResult').innerHTML='<div class="social-loading">Searching…</div>';if(!key)return;const name=await getDoc(doc(db,'usernames',key));if(!name.exists())return $('#searchResult').innerHTML='<div class="empty-state compact">No player found with that exact name.</div>';const uid=name.data().uid;if(uid===user.uid)return $('#searchResult').innerHTML='<div class="empty-state compact">That is your own account.</div>';const pub=await getDoc(doc(db,'publicProfiles',uid)),data=pub.exists()?pub.data():{uid,displayName:name.data().displayName};const existing=relationships.find(x=>x.members?.includes(uid));$('#searchResult').innerHTML=profileCard(data,existing)}
function profileCard(p,rel){let action=`<button class="button" data-add="${p.uid}">Add friend</button>`;if(rel?.status==='accepted')action='<span class="social-tag success">Friends</span>';if(rel?.status==='pending')action='<span class="social-tag">Request pending</span>';if(rel?.status==='blocked')action='<span class="social-tag danger">Blocked</span>';setTimeout(()=>document.querySelector(`[data-add="${p.uid}"]`)?.addEventListener('click',()=>sendRequest(p.uid,p.displayName)),0);return `<article class="friend-card"><div class="friend-avatar">${esc(p.displayName?.[0]||'?')}</div><div><h3>${esc(p.displayName||'Player')}</h3><p>Human Skills Tester player</p></div><div class="friend-actions"><a class="button secondary" href="player.html?uid=${encodeURIComponent(p.uid)}">View stats</a>${action}</div></article>`}
async function sendRequest(uid,name){const id=pair(user.uid,uid),existing=await getDoc(doc(db,'friendships',id));if(existing.exists())return notice('A relationship already exists with this player.',true);await setDoc(doc(db,'friendships',id),{members:[user.uid,uid],names:{[user.uid]:profile.displayName,[uid]:name},requestedBy:user.uid,status:'pending',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});notice('Friend request sent.');await refresh()}
function renderRequests(incoming,sent){$('#incoming').innerHTML=incoming.length?incoming.map(x=>requestRow(x,true)).join(''):'<div class="empty-state compact">No incoming requests.</div>';$('#sent').innerHTML=sent.length?sent.map(x=>requestRow(x,false)).join(''):'<div class="empty-state compact">No sent requests.</div>';document.querySelectorAll('[data-accept]').forEach(b=>b.onclick=()=>accept(b.dataset.accept));document.querySelectorAll('[data-decline]').forEach(b=>b.onclick=()=>decline(b.dataset.decline))}
function other(rel){return rel.members.find(x=>x!==user.uid)}function requestRow(rel,incoming){const uid=other(rel),name=rel.names?.[uid]||'Player';return `<div class="request-row"><span>${esc(name)}</span><div>${incoming?`<button class="button" data-accept="${rel.id}">Accept</button>`:''}<button class="button secondary" data-decline="${rel.id}">${incoming?'Decline':'Cancel'}</button></div></div>`}
async function accept(id){await updateDoc(doc(db,'friendships',id),{status:'accepted',acceptedAt:serverTimestamp(),updatedAt:serverTimestamp()});await refresh()}async function decline(id){await deleteDoc(doc(db,'friendships',id));await refresh()}
async function renderFriends(list){if(!list.length){$('#friendsList').innerHTML='<div class="empty-state">No friends yet. Search for an exact display name to get started.</div>';return}const presence=(await get(ref(rtdb,'socialPresence'))).val()||{};$('#friendsList').innerHTML=list.map(rel=>{const uid=other(rel),name=rel.names?.[uid]||'Player',p=presence[uid]||{},online=p.state==='online',join=online&&p.joinable&&p.roomId?`<a class="button" href="multiplayer.html?room=${encodeURIComponent(p.roomId)}">Join game</a>`:'';return `<article class="friend-card"><div class="friend-avatar ${online?'online':''}">${esc(name[0])}</div><div><h3>${esc(name)}</h3><p>${online?activity(p):'Offline'}</p></div><div class="friend-actions">${join}<a class="button secondary" href="player.html?uid=${uid}">View stats</a><button class="text-button danger-text" data-remove="${rel.id}">Remove</button><button class="text-button" data-block="${rel.id}">Block</button></div></article>`}).join('');document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>decline(b.dataset.remove));document.querySelectorAll('[data-block]').forEach(b=>b.onclick=()=>block(b.dataset.block))}
function activity(p){if(p.activity==='multiplayer')return `${p.joinable?'Joinable':'Playing'} · ${p.gameType||'game'} · ${p.rounds||1} rounds`;return 'Online'}
async function block(id){await updateDoc(doc(db,'friendships',id),{status:'blocked',blockedBy:user.uid,updatedAt:serverTimestamp()});await refresh()}
function renderBlocked(list){$('#blocked').innerHTML=list.length?list.map(x=>`<div class="request-row"><span>${esc(x.names?.[other(x)]||'Player')}</span><button class="button secondary" data-unblock="${x.id}">Unblock</button></div>`).join(''):'<div class="empty-state compact">No blocked players.</div>';document.querySelectorAll('[data-unblock]').forEach(b=>b.onclick=()=>decline(b.dataset.unblock))}
boot().catch(e=>notice(e.message,true));
