import {auth,onAuthStateChanged,signOut,signInAnonymously,profileFor,ref,set,onValue,onDisconnect,rtdbTimestamp,rtdb} from './firebase.js';
let resolved=false;
export const ready=new Promise(resolve=>onAuthStateChanged(auth,async user=>{
 if(!user&&!resolved){resolved=true;try{await signInAnonymously(auth);return}catch(e){console.warn(e)}}resolved=true;window.hstUser=user||null;let profile=null;
 if(user&&!user.isAnonymous){try{profile=await profileFor(user.uid)}catch(e){console.warn(e)}}window.hstProfile=profile;paint(user,profile);if(user)setupPresence(user,profile);resolve({user,profile});
}));
function paint(user,profile){const signed=user&&!user.isAnonymous;document.querySelectorAll('[data-auth-area]').forEach(el=>{el.innerHTML=signed?`<a href="profile.html" class="account-pill">${esc(profile?.displayName||user.displayName||'Finish profile')}</a><button class="nav-signout" data-signout>Sign out</button>`:`<a href="login.html" class="account-pill">Sign in</a>`});document.querySelectorAll('[data-signout]').forEach(b=>b.onclick=async()=>{await signOut(auth);location.href='index.html'})}
function setupPresence(user,profile){const sid=sessionStorage.getItem('hst_session_id')||crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;sessionStorage.setItem('hst_session_id',sid);const session=ref(rtdb,`activeSessions/${user.uid}/${sid.replace(/[.#$\[\]/]/g,'_')}`),connected=ref(rtdb,'.info/connected');onValue(connected,async s=>{if(!s.val())return;try{await onDisconnect(session).remove();await set(session,{state:'online',signedIn:!user.isAnonymous,displayName:user.isAnonymous?'Guest':profile?.displayName||user.displayName||'Player',lastChanged:rtdbTimestamp()});if(!user.isAnonymous){const social=ref(rtdb,`socialPresence/${user.uid}`);await onDisconnect(social).set({state:'offline',lastSeen:rtdbTimestamp()});await set(social,{state:'online',activity:'browsing',joinable:false,lastSeen:rtdbTimestamp()})}}catch(e){console.warn('Presence unavailable',e)}});onValue(ref(rtdb,'activeSessions'),snap=>{let count=0;snap.forEach(u=>{if(u.exists())count++});document.querySelectorAll('[data-online-count]').forEach(el=>el.textContent=String(count));document.querySelectorAll('[data-online-label]').forEach(el=>el.textContent=count===1?'player online':'players online')})}
function esc(v){return String(v).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
